title: 'monsoon'
description: 'Welcome to my blog'
url: 'https://monsoon.cl'

paginate: 6
permalink: /:year/:month/:day/:title/

kramdown:
  hard_wrap: true

sass:
  style: :compressed
  sass_dir: assets/stylesheets

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-category-pages
  - jekyll-redirect-from
