title: "monsoon"
author: "Shi"
description: "blog"
url: "http://monsoon.cl"

highlighter: pygments
permalink: pretty

paginate: 6
paginate_path: "page:num"

sass:
  style: :compressed
  sass_dir: _sass