title: 'monsoon'
description: 'Welcome to my blog'
url: 'https://monsoon.cl'

permalink: /:year/:month/:day/:title/

kramdown:
  hard_wrap: true

sass:
  style: :compressed
  sass_dir: assets/stylesheets

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 6
  title: 'Page :num · :title'
  permalink: '/page/:num/'
  sort_reverse: true
