title: &title "monsoon"
name: *title
author: "Lejia Chen"
description: "Welcome to my blog"
url: "https://monsoon.cl"
baseurl: ""

permalink: pretty

paginate: 6
paginate_path: "/page:num/"

sass:
  style: :compressed
  sass_dir: assets/stylesheets

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
