title: &title "monsoon"
name: *title
author: "Shi"
description: "Welcome to my blog"
url: "http://monsoon.cl"

permalink: pretty

paginate: 6
paginate_path: "page:num"

sass:
  style: :compressed
  sass_dir: _sass

gems:
  - jekyll-paginate
  - jekyll-feed
